[build]
  command = "python -m pip install --upgrade pip setuptools wheel && python -m pip install -r /path/to/requirements.txt && python app.py"
  publish = "public"

[context.production.environment]
  HUGGINGFACE_API_KEY = "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"
