[build]
  command = "python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt"
  publish = "public"

[context.production.environment]
  HUGGINGFACE_API_KEY = "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"
