[build]
  command = "python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt && python app.py"
  publish = "public"

[context.production.environment]
  HUGGINGFACE_API_KEY = "your_api_key"
